src/sass/components/_table.scss

Fix the case of checkboxes in table

---

src/sass/components/_hero-banner.scss
src/sass/components/_page-header.scss
src/sass/patterns/__patterns.scss
src/sass/patterns/_features-table.scss
src/sass/patterns/_price-box.scss
src/sass/patterns/_testimonials.scss

+ Fix lorem pixel img
+ rename page-header alone option

Add pricing box & features table

---

src/sass/patterns/__patterns.scss
src/sass/patterns/_blog-article-meta.scss
src/sass/patterns/_blog-article.scss
src/sass/structures/_blog-post.scss
src/sass/structures/_blogroll.scss
src/template/structures/blog-post.html

+ Split blog article meta as a new pattern
+ Use the blog article meta in blog-post structure

fix Blogroll and Blog Post

---

src/sass/components/__components.scss
src/sass/components/_browser.scss
src/sass/components/_business-card.scss
src/sass/structures/_blog-post.scss
src/sass/structures/_blogroll.scss
src/sass/structures/_featured-page.scss
src/sass/structures/_mozaic.scss
src/template/sass-kss/modules/_structures-demo.scss

Browser component

---

src/sass/components/_dot.scss
src/sass/components/_tooltip.scss
src/sass/patterns/__patterns.scss
src/sass/patterns/_tooltip-interactive.scss

Add interactive tooltip & texts in dots

---

src/sass/components/_button.scss

Review default button hover & focus state (from light grey to light blue)

---

package.json
woo-components/package.json

Bump version 8.1.3

---

package.json
src/svg/01-basic/loader.svg
woo-components/package.json

> Revert legacy loader icon for correct animation.

Loader icon spin

---

package.json
src/sass/patterns/_page-footer.scss
src/sass/utils/_mixins.scss
src/template/index.html
woo-components/package.json

> New Footer Markup
> New Footer styling
> Bump version
> Fix styleguide footer (not related to new footer)

New header footer

---

package.json
src/sass/patterns/_navbar.scss
src/sass/utils/_generics.scss
src/template/index.html
src/template/public/scripts.js
woo-components/package.json

> Add support to header collapse menu to right side
> Bump styleguide version
> Set styleguide collapse menu to right side

Header right toggle

---

package.json
src/sass/patterns/_page-footer.scss
src/template/index.html
src/template/structures/blog-post.html
src/template/structures/blogroll.html
src/template/structures/featured-page.html
src/template/structures/mozaic.html
woo-components/package.json

* Improve Social footer icons on mobile
* Improve new footer naming convention
* Version bumping

Page footer naming

---

package.json
src/sass/colors/_colors-basics.scss
src/sass/components/_alert.scss
src/sass/utils/_variables.scss
src/template/sass-kss/modules/_colors-render.scss
woo-components/package.json

* Add "-darker" variation on all colors
* Add "-light", "-lighter" variation on 'turquoise', 'emerald', 'amethyst', 'competitor'
* Update palette to start from "-darker" variation
* Fix navigation bar having a max-height on large screens
* Bump versions

Primary darker

---

gulpfile.js
package.json
src/sass/patterns/_page-footer.scss
src/template/public/scripts.js
src/template/sass-kss/kss-parts/_sidebar.scss
woo-components/package.json

* Footer
* Add 60px margin-top
* Improve footer menu contrast
* Improvements
* Improve sidebar navigation
* Improve footer not going off-bounds
* Bump version

Footer margins

---

package.json
src/sass/components/_form.scss
src/sass/utils/_variables.scss

* Allowing input-addons for CTAs and competitor dots aligned inside inputs

Input addon

---

package.json
src/sass/patterns/_generation-bar.scss

* Fluid fullscreen genbar class decorator

Genbar fluid

---

package.json
src/sass/patterns/_generation-bar.scss

* Avoid shrinking on genbar elements

Genbar shrink

---

package.json
src/sass/patterns/_generation-bar.scss

Genbar input fix

---

package.json
src/sass/patterns/_generation-bar.scss
src/sass/utils/_generics.scss

* No Body height based on percentage

Body height

---

circle.yml
package.json

* Rename `publish` script to `deploy`
* Update license to `MIT`

rename publish script, update to mit license

---

.circleci/config.yml

Publish to NPM version if not exists

---

package.json
src/sass/components/_dropdown.scss

- Chevrons were updated, so this should have been updated too

Chevrons in dropdown-up updated

---

package.json
src/sass/utils/_bootstrap.scss
src/sass/woorank-theme.scss

* Import Bootstrap manually, excluding media print
* bump version

Remove print media

---

package.json
src/sass/structures/_blog-post.scss

* Add `image-right` and `image-left` classes for align images on blog layout
* Bump NPM version

Blog image sides

---

package.json
src/sass/structures/_blog-post.scss

* Support full width images with `?align=full` param
* Bump version

Image full

---

package.json

Npm version

---

gulpfile.js
package.json
src/template/index.html

Now the `svg` folder looks like below SS after build

New gulp task - Build icons inside svg folder without sub directories

---

package.json
src/sass/icons/_icons-applications.scss
src/svg/07-application/audit.svg

* Npm bump version
* Add audit icon

Audit icons

---

.circleci/config.yml

- Update cci config file to use run instead of deploy:
https://circleci.com/docs/migrate-from-deploy-to-run/

replace deploy with run
